# Generated by Django 5.2.7 on 2025-11-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='barangay_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/barangay_ids/'),
        ),
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pwd_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pwd_ids/'),
        ),
        migrations.AddField(
            model_name='account',
            name='senior_citizen_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/senior_ids/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
