# Generated by Django 5.2.7 on 2025-10-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='users',
        ),
    ]
