# Generated by Django 5.2.7 on 2025-10-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='posted_by',
        ),
    ]
